services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
  php:
    build:
      context: .
      dockerfile: php/Dockerfile
    volumes:
      - ./php:/var/www/html
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: raflidb
      MYSQL_USER: rafli
      MYSQL_PASSWORD: rafli123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./migration:/docker-entrypoint-initdb.d

volumes:
  db_data: