services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./php:/var/www/html:z
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:z
    depends_on:
      - php
      - db
  php:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./php:/var/www/html:z
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: raflidb
      MYSQL_USER: rafli
      MYSQL_PASSWORD: rafli123
      MYSQL_ROOT_PASSWORD: root123
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql:Z

volumes:
  db_data:
